sylius_admin_menu:
  flags:
    extends: admin_menu
  value:
    'catalog':
      label: 'Catalog'
    'sales':
      label: 'Sales'
    'customers':
      label: 'Customers'
    'marketing':
      label: 'Marketing'
    'configuration':
      label: 'Configuration'
sylius_attribute_type:
  flags:
    extends: attribute_type
    sort: label
    filter: disabled
  value:
    text:
      schema_type: string
      type_hint: string
      templates: []
    product_attribute:
      disabled: true
    product_attribute_multiselect:
      disabled: true
    product_attribute_set:
      disabled: true
    product_attribute_set_multiselect:
      disabled: true
    country:
      disabled: true
    country_multiselect:
      disabled: true
    date:
      schema_type: datetime
      type_hint: "\\DateTime"
    decimal:
      schema_type: decimal
      type_hint: "float"
      schema_attributes: ' precision="10" scale="5"'
    dropdown:
      disabled: true
    file:
      disabled: true
    image:
      disabled: true
    integer:
      schema_type: integer
      type_hint: int
    multiselect:
      disabled: true
    textarea:
      schema_type: text
      type_hint: string
    wysiwyg:
      disabled: true
    yesno:
      schema_type: boolean
      type_hint: bool
    dynamic:
      disabled: true
