code:
  id: code
  type: text
  options:
    label: Attribute Code
    attr:
      data-validation: custom
      data-validation-regexp: "^[a-z_]+"
      data-validation-error-msg: "Attribute code must consist only of letters and underscore"
      title: "This is the attribute code. It will be used in the logic of the extension. Use only letters (a-z), numbers (0-9) or underscore(_) in this field, first character should be a letter. There are some naming restriction. For example the code cannot be: 'data', 'child'"
label:
  id: label
  type: text
  options:
    label: Label
    attr:
      class: 'label'
      title: This is the attribute label that will be visible in the back-end in the add/edit form and in some cases in frontend.
type:
  id: type
  type: attribute_type
  has_default: true
  options:
    label: Attribute Type
    attr:
      umc-type: type
      title: This is the attribute type. This wil determine the table column type for this field/attribute and its behavior.
is_name:
  id: is_name
  type: radio
  options:
    label: Acts as name
    attr:
      class: is-name
      umc-type: is-name
      title: Each entity must have an attribute to behave as 'Name'. This attribute will be used to identify different entities among themselves. It will also be used in dropdowns with entities. This option is available only for text, number and decimal attributes.
required:
  id: required
  type: choice
  has_default: true
  options:
    label: Required
    attr:
      umc-type: required
      title: This sets the attribute as required in the admin add/edit form
    choices:
      Yes: 1
      No: 0
position:
  id: position
  type: text
  options:
    label: Sort order
    required: false
    attr:
      title: The sort order of the field in form and grid.
admin_grid:
  id: admin_grid
  type: choice
  has_default: true
  options:
    label: Show in admin grid
    attr:
      umc-type: admin-grid
      title: "This allows you to display the attribute as a column in the admin grid of the entity. The attribute set to behave as 'Name' will be included by default in the grid."
    choices:
      Yes: 1
      No: 0
      Yes but hidden: 2
admin_grid_filter:
  id: admin_grid_filter
  type: choice
  has_default: true
  options:
    label: Filterable in admin grid
    attr:
      umc-type: admin-grid-filter
      title: If this is set to yes, your field will be filtrable in the admin grid
    choices:
      Yes: 1
      No: 0
options:
  id: options
  type: textarea
  options:
    required: false
    label: Options in select
    attr:
      umc-type: options
      title: If you choose to enter the values for the dropdown or multiselect manually, input them here. Separate the options with a new line.
default_value:
  id: default_value
  type: textarea
  options:
    required: false
    label: Default value (one per line for multiselects)
    attr:
      title: Fill in a default value for the attribute. Leave empty for no value. For dropdown and multiselect attributes the value, must be a valid value. not valid ones will be removed. For the multiselect attributes add one default value on each line. For Yes/No attribtues enter 1 for Yes, 0 for No. For country attributes fill in the country ISO2 code. You cannot set a default value for image and file attributes.For the moment the default values don't work for all the form elements defined via ui components V2.2.
note:
  id: note
  type: text
  options:
    required: false
    label: Note
    attr:
      title: This will be added as a comment under the field in the admin add/edit form.
