panel:
  field: label_singular
  default: New Entity
children:
  _attributes: Attribute
settings_label: "Module default settings"
rows:
  -
    name_singular:
      name: name_singular
      type: text
      label: Name Singular
      dataValidation: validate_required
      title: Each entity must have a label used for buttons, links, messages. This is the singular form of the label. For example in a blog module, the post entity will have the label in singular form 'Post'
      col: 3
    name_plural:
      name: name_plural
      type: text
      label: Name Plural
      dataValidation: validate_required
      title: "This is the plural value of the entity code. For example 'posts'."
      col: 3
    label_singular:
      name: label_singular
      type: text
      label: Label Singular
      dataValidation: validate_required
      title: UMC generates the code in a 'human readable' form. It's easier to figure out what the code is about when the variables and methods have a propper name.For example it's easier to read foreach ($posts as $_post){...} or $post->getTags() than foreach ($list as $item){...} or $entity->getRelated('tags');The value you fill in here will be used for variable names, file names and table names.
      col: 3
    label_plural:
      name: label_plural
      type: text
      label: Label Plural
      dataValidation: validate_required
      title: "This is the plural form of the label above. It will be used for lists. (For example: 'Posts'). Try to use English words for this label. It's not mandatory, but it makes the taxonomy more readable. I recommend the first letter to be uppercase."
      col: 3
  -
    search:
      name: search
      type: checkbox
      has_default: true
      label: Use in global search
      dataValidation: validate_required
      title: The Magento admin Global search (at the top of every admin page) searches for the text you enter in products, customers and orders. If you set this to 'Yes' than it will search in your entity also.
      col: 2
    store:
      name: store
      type: checkbox
      has_default: true
      label: Associate to store views
      dataValidation: validate_required
      title: Selecting "Yes" it will add a multiselect field in the add / edit form for the entity that will allow you to select the associated stores. Similar to CMS blocks and pages
      col: 2
    frontend_list:
      name: frontend_list
      type: checkbox
      has_default: true
      label: Create Frontend list page
      dataValidation: validate_required
      title: If this is set to 'Yes', a page that lists your entities will be created. The page has a toolbar for pagination.
      col: 2
    frontend_view:
      name: frontend_view
      type: checkbox
      has_default: true
      label: Create Frontend view page
      dataValidation: validate_required
      title: If this is set to 'Yes', a page that shows the details of your entity instance will be created.
      col: 2
    seo:
      name: seo
      type: checkbox
      has_default: true
      label: Add SEO attributes
      dataValidation: validate_required
      title: If this is set to 'Yes', 3 extra fields/attributes will be added to your entity, 'meta_title', 'meta_keywords' and 'meta_description'. The values of these fields/attributes will be added used for the details page of your entity.
      additionalDataBind: 'enable: data.frontend_view'
      col: 2
    menu_link:
      name: menu_link
      type: choice
      has_default: true
      label: Menu to Link zone
      optionProvider: 'frontend_menu_link'
      dataValidation: validate_required
      title: If the entity has a frontend list page you can place the link to it in 2 sections of the website
      additionalDataBind: 'enable: data.frontend_list'
      col: 2
