panel:
  field: null
  default: Module information
children:
  _entities: Entity
settings_label: "Module default settings"
rows:
  - umc_crud:
      name: umc_crud
      type: checkbox
      label: I have Umc_Crud module installed
      required: false
      title: Umc_Crud description goes here
      has_default: true
      col: 2
    namespace:
      name: namespace
      type: text
      has_default: true
      label: Namespace
      dataValidation: validate_required validate_custom
      dataValidationRegexp: "^[A-Z][a-zA-Z0-9]+"
      dataValidationErrorMsg: "Namespace must be alphanumerical and start with a capital letter"
      title: "This is the folder name of your new extension. Your company name should go here. Use only letters and numbers. Start with a capital letter."
      col: 5
    module_name:
      name: module_name
      type: text
      label: Module Name
      dataValidation: custom
      dataValidationRegexp: "^[A-Z][a-zA-Z0-9]+"
      dataValidationErrorMsg: "Module name must be alphanumerical and start with a capital letter"
      title: "This is your extension/module name. It should be something meaningful and not very long. Try to use a noun in singular form. Start with a capital letter."
      col: 5
  -
    menu_text:
      name: menu_text
      type: text
      label: Admin menu title
      dataValidation: validate_required
      title: This is the title that will be added to the menu.
      col: 4
    menu_parent:
      name: menu_parent
      type: choice
      has_default: true
      label: Admin parent menu ID
      required: false
      data-pretty-select: 'true'
      title: This is the parent menu id of the module menu. Leave empty to add in top menu.
      optionProvider: 'admin_menu'
      col: 4
    sort_order:
      name: sort_order
      type: text
      label: Admin menu sort order
      dataValidation: validate_required number
      dataValidationErrorMsg: "Sort order must be a number"
      title: This is the sort order in the menu.
      col: 4
  -
    config_tab:
      name: config_tab
      type: text
      label: Store -> Config tab name.
      required: false
      title: If at least one entity has frontend files then a section in Stores->Configuration will be created. Fill in the tab name here. Leave empty to use the namespace.
      col: 6
    config_tab_position:
      name: config_tab_position
      type: text
      label: Stores -> Configuration tab position
      required: false
      dataValidation: validate_number
      title: If at least one entity has frontend files then a section in System->Configuration will be created. Fill in the tab position. The higher the number the lower it will appear in the list.
      col: 6
  -
    front_key:
      name: front_key
      type: text
      label: Frontend URL Key
      required: false
      title: This is the url key for the module in case you add any entities that support frontend. Leave empty to autogenerate
      col: 6
    license:
      name: license
      type: textarea
      has_default: true
      label: License
      required: false
      title: The text you put here will be added at the top of (almost) each file in the module you create. Use {{Namespace}} as a placeholder for namespace, {{Module}} as a placeholder for the module name and {{Y}} as placeholder for current year. If you don't want any License text on your files just leave this field empty.
      col: 6
