namespace:
  id: namespace
  type: text
  has_default: true
  options:
    label: Namespace
    attr:
      data-validation: custom
      data-validation-regexp: "^[A-Z][a-zA-Z0-9]+"
      data-validation-error-msg: "Namespace must be alphanumerical and start with a capital letter"
      title: "This is the folder name of your new extension. Your company name should go here. Use only letters and numbers. Start with a capital letter."
module_name:
  id: module_name
  type: text
  options:
    label: Module Name
    attr:
      data-validation: custom
      data-validation-regexp: "^[A-Z][a-zA-Z0-9]+"
      data-validation-error-msg: "Module name must be alphanumerical and start with a capital letter"
      title: "This is your extension/module name. It should be something meaningful and not very long. Try to use a noun in singular form. Start with a capital letter."
version:
  id: version
  type: text
  has_default: true
  options:
    label: Version
    attr:
      data-validation: custom
      data-validation-regexp: "^(?:[\\dx]{1,3}\\.){0,3}[\\dx]{1,3}$"
      data-validation-error-msg: "Version should have the format x.[y[.z[.t]]]"
      title: This is the version of the module.
menu_text:
  id: menu_text
  type: text
  options:
    label: Admin menu title
    attr:
      title: This is the title that will be added to the menu.
menu_parent:
  id: menu_parent
  type: menu
  has_default: true
  options:
    label: Admin parent menu ID
    required: false
    attr:
      data-validation: custom
      data-validation-regexp: "^[A-Z][a-zA-Z0-9]+_[A-Z][a-zA-Z0-9]+::[a-zA-Z0-9]+"
      data-validation-error-msg: "Parent menu title must have the format 'Namespace_Module::resource'"
      title: This is the parent menu id of the module menu. Leave empty to add in top menu.
sort_order:
  id: sort_order
  type: number
  options:
    label: Admin menu sort order
    attr:
      data-validation: number
      data-validation-error-msg: "Sort order must be a number"
      title: This is the sort order in the menu.
license:
  id: license
  type: textarea
  has_default: true
  options:
    label: License
    required: false
    attr:
      title: The text you put here will be added at the top of (almost) each file in the module you create. Use {{Namespace}} as a placeholder for namespace, {{Module}} as a placeholder for the module name and {{Y}} as placeholder for current year. If you don't want any License text on your files just leave this field empty.
