panel:
  field: label
  default: New Option
children: []
settings_label: "Attribute Option default settings"
rows:
  -
    value:
      name: value
      type: text
      label: Option value
      title: "Option value"
      dataValidation: validate_required
      col: 12
  -
    label:
      name: label
      type: text
      label: Label
      title: Option label
      dataValidation: validate_required
      col: 12
  -
    default_radio:
      name: default_radio
      type: checkbox
      label: "Default"
      title: "Default"
      containerAttributes: 'data-bind="visible: $parent.isDropdown"'
      col: 12
  -
    default_checkbox:
      name: default_checkbox
      type: checkbox
      label: "Default"
      title: "Default"
      containerAttributes: 'data-bind="visible: $parent.isMultiselect"'
      col: 12
