panel:
  field: label
  default: New Serialized Field
children:
  _options: Option
settings_label: "Serialized field default settings"
rows:
  -
    code:
      name: code
      type: text
      label: Attribute Code
      dataValidation: custom
      dataValidationRegexp: "^[a-z_]+"
      dataValidationErrorMsg: "Attribute code must consist only of letters and underscore"
      title: "This is the attribute code. It will be used in the logic of the extension. Use only letters (a-z), numbers (0-9) or underscore(_) in this field, first character should be a letter. There are some naming restriction. For example the code cannot be: 'data', 'child'"
      col: 4
    label:
      name: label
      type: text
      label: Label
      dataValidation: validate_required
      title: This is the attribute label that will be visible in the back-end in the add/edit form and in some cases in frontend.
      col: 4
    type:
      name: type
      type: choice
      has_default: true
      label: Attribute Type
      dataValidation: validate_required
      data-pretty-select: 'true'
      optionProvider: 'serialized_field_type'
      title: This is the field type.
      col: 4
  -
    required:
      name: required
      type: checkbox
      has_default: true
      label: Required
      title: This sets the attribute as required in the admin add/edit form
      col: 4
    show_in_list:
      name: show_in_list
      type: checkbox
      has_default: true
      label: Show in frontend list page
      dataValidation: validate_required
      title: "This allows you to display the attribute in the entity list page on frontend"
      additionalDataBind: 'enable: $parent.data.show_in_list'
      col: 4
    show_in_view:
      name: show_in_view
      type: checkbox
      has_default: true
      label: Show in frontend view page
      title: "This allows you to display the attribute in the entity view page on frontend"
      additionalDataBind: 'enable: $parent.data.show_in_view'
      col: 4
  -
    note:
      name: note
      type: text
      required: false
      label: Note
      title: This will be added as a comment under the field in the admin add/edit form.
      col: 4
    tooltip:
      name: tooltip
      type: text
      required: false
      label: Tooltip
      title: This will be added as a tooltip in the admin add / edit form
      col: 4
    default_value:
      name: default_value
      type: textarea
      required: false
      label: Default value (one per line for multiselects)
      title: Fill in a default value for the attribute. Leave empty for no value. For dropdown and multiselect attributes the value, must be a valid value. not valid ones will be removed. For the multiselect attributes add one default value on each line. For Yes/No attribtues enter 1 for Yes, 0 for No. For country attributes fill in the country ISO2 code. You cannot set a default value for image and file attributes.For the moment the default values don't work for all the form elements defined via ui components V2.2.
      col: 4
