controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

umc_core:
    resource: ../../src/Umc/CoreBundle/Controller/
    type: annotation
