dynamic:
  panel:
    field: label
    default: New Dynamic Field
  children:
    -
      code: _option
      className: Option
      tabLabel: Options
      formKey: option
      sortable: sortableListOptions
      visible: "data.type() === 'dropdown' || data.type() === 'multiselect'"
      addButton:
        label: Add Option
  tabs:
    -
      label: Name settings
      code: name
      sort_order: 10
      cols: 4
    -
      label: Admin
      code: admin
      sort_order: 20
      cols: 6
    -
      label: Frontend
      code: frotnend
      sort_order: 30
    -
      label: Misc
      code: misc
      sort_order: 40
  fields:
    -
      name: code
      type: text
      label: Attribute Code
      dataValidation: custom
      dataValidationRegexp: "^[a-z_]+"
      dataValidationErrorMsg: "Attribute code must consist only of letters and underscore"
      title: "This is the attribute code. It will be used in the logic of the extension. Use only letters (a-z), numbers (0-9) or underscore(_) in this field, first character should be a letter. There are some naming restriction. For example the code cannot be: 'data', 'child'"
      tab: name
    -
      name: label
      type: text
      label: Label
      dataValidation: validate_required
      title: This is the attribute label that will be visible in the back-end in the add/edit form and in some cases in frontend.
      tab: name
    -
      name: type
      type: choice
      has_default: true
      label: Attribute Type
      dataValidation: validate_required
      options: '%magento_dynamic_rows_type%'
      title: This is the field type.
      tab: name
    -
      name: required
      type: checkbox
      has_default: true
      label: Required
      title: This sets the attribute as required in the admin add/edit form
      tab: name
    -
      name: show_in_list
      type: checkbox
      has_default: true
      label: Show in frontend list page
      dataValidation: validate_required
      title: "This allows you to display the field in the entity list page on frontend"
      additionalDataBind: 'enable: $parent.data.show_in_list'
      tab: frontend
    -
      name: show_in_view
      type: checkbox
      has_default: true
      label: Show in frontend view page
      title: "This allows you to display the field in the entity view page on frontend"
      additionalDataBind: 'enable: $parent.data.show_in_view'
      tab: frontend
    -
      name: note
      type: text
      required: false
      label: Note
      title: This will be added as a comment under the field in the admin add/edit form.
      tab: misc
    -
      name: tooltip
      type: text
      required: false
      label: Tooltip
      title: This will be added as a tooltip in the admin add / edit form
      tab: misc
    -
      name: default_value
      type: textarea
      required: false
      label: Default value (one per line for multiselects)
      title: Fill in a default value for the attribute. Leave empty for no value. For dropdown and multiselect attributes the value, must be a valid value. not valid ones will be removed. For the multiselect attributes add one default value on each line. For Yes/No attribtues enter 1 for Yes, 0 for No. For country attributes fill in the country ISO2 code. You cannot set a default value for image and file attributes.For the moment the default values don't work for all the form elements defined via ui components V2.2.
      tab: misc
