option:
  code: option
  panel:
    field: label
    default: New Option
  children: []
  tabs:
    -
      label: Settings
      code: base
      sort_order: 10
      cols: 4
  fields:
    -
      name: value
      type: text
      label: Option value
      title: "Option value"
      dataValidation: validate_required
      tab: base
      sort_order: 10
    -
      name: label
      type: text
      label: Label
      title: Option label
      dataValidation: validate_required
      tab: base
    -
      name: default_radio
      type: radio
      label: "Default"
      title: "Default"
      containerAttributes: 'data-bind="visible: $parent.isDropdown"'
      tab: base
    -
      name: default_checkbox
      type: checkbox
      label: "Default"
      title: "Default"
      containerAttributes: 'data-bind="visible: $parent.isMultiselect"'
      tab: base
