namespace:
  id: namespace
  type: text
  has_default: true
  options:
    label: Namespace
    attr:
      data-validation: validate_required validate_custom
      data-validation-regexp: "^[A-Z][a-zA-Z0-9]+"
      data-validation-error-msg: "Namespace must be alphanumerical and start with a capital letter"
      title: "This is the folder name of your new extension. Your company name should go here. Use only letters and numbers. Start with a capital letter."
  sort: 5
module_name:
  id: module_name
  type: text
  options:
    label: Module Name
    attr:
      data-validation: custom
      data-validation-regexp: "^[A-Z][a-zA-Z0-9]+"
      data-validation-error-msg: "Module name must be alphanumerical and start with a capital letter"
      title: "This is your extension/module name. It should be something meaningful and not very long. Try to use a noun in singular form. Start with a capital letter."
  sort: 10
version:
  id: version
  type: text
  has_default: true
  options:
    label: Module Version
    attr:
      data-validation: custom
      data-validation-regexp: "^(?:[\\dx]{1,3}\\.){0,3}[\\dx]{1,3}$"
      data-validation-error-msg: "Version should have the format x[.y[.z[.t]]]"
      title: This is the version of the module.
  sort: 20
magento_version:
  id: magento_version
  type: choice
  has_default: true
  options:
    label: Magento Version
    choices:
      2.2.*: 2.2
      2.3.*: 2.3
    attr:
      data-validation: validate_required
      title: This is the Magento version for which you are creating the module
  sort: 30
menu_text:
  id: menu_text
  type: text
  options:
    label: Admin menu title
    attr:
      data-validation: validate_required
      title: This is the title that will be added to the menu.
  sort: 40
menu_parent:
  id: menu_parent
  type: menu
  has_default: true
  options:
    label: Admin parent menu ID
    required: false
    attr:
      data-pretty-select: 'true'
      title: This is the parent menu id of the module menu. Leave empty to add in top menu.
  sort: 50
sort_order:
  id: sort_order
  type: number
  options:
    label: Admin menu sort order
    attr:
      data-validation: validate_required number
      data-validation-error-msg: "Sort order must be a number"
      title: This is the sort order in the menu.
  sort: 60
