-
  source: Api/Data/_Entity_Interface.php
  label: "Entity data interface"
  scope: entity
-
  source: Api/Data/_Entity_SearchResultInterface.php
  label: "Entity search result interface"
  scope: entity
-
  source: Api/_Entity_ListRepositoryInterface.php
  label: "Entity list repository interface"
  scope: entity
-
  source: Api/_Entity_RepositoryInterface.php
  label: "Entity repository interface"
  scope: entity
-
  source: Controller/Adminhtml/_Entity_/Index.php
  label: "Entity index controller action"
  scope: entity
-
  source: Controller/Adminhtml/_Entity_/Delete.php
  label: "Delete entity controller action"
  scope: entity
-
  source: Controller/Adminhtml/_Entity_/Edit.php
  label: "Edit entity controller action"
  scope: entity
-
  source: Controller/Adminhtml/_Entity_/NewAction.php
  label: "New entity controller action"
  scope: entity
-
  source: Controller/Adminhtml/_Entity_/InlineEdit.php
  label: "Inline edit entity controller action"
  scope: entity
-
  source: Controller/Adminhtml/_Entity_/MassDelete.php
  label: "Mass delete entity controller action"
  scope: entity
-
  source: Controller/Adminhtml/_Entity_/Save.php
  label: "Save entity controller action"
  scope: entity
-
  source: Controller/Adminhtml/_Entity_/File/Upload.php
  label: "Entity file upload controller action"
  scope: entity
-
  source: Controller/Adminhtml/_Entity_/Image/Upload.php
  label: "Entity image upload controller action"
  scope: entity
-
  source: Model/_Entity_SearchResults.php
  label: "Entity search results model"
  scope: entity
-
  source: Model/_Entity_.php
  label: "Entity model"
  scope: entity
-
  source: Model/ResourceModel/_Entity_.php
  label: "Entity resource model"
  scope: entity
-
  source: Model/ResourceModel/_Entity_/Collection.php
  label: "Entity collection resource model"
  scope: entity
-
  source: view/adminhtml/layout/_modulename___entity__edit.xml
  label: "Entity admin edit layout handle"
  scope: entity
-
  source: view/adminhtml/layout/_modulename___entity__index.xml
  label: "Entity admin index layout handle"
  scope: entity
-
  source: view/adminhtml/ui_component/_modulename___entity__listing.xml
  label: "Entity admin grid ui component"
  scope: entity
-
  source: view/adminhtml/ui_component/_modulename___entity__form.xml
  label: "Entity admin grid ui component"
  scope: entity
-
  source: Model/_Entity_Repo.php
  label: "Entity repository model"
  scope: entity
-
  source: Model/_Entity_ListRepo.php
  label: "Entity List repository model"
  scope: entity
-
  source: Model/_Entity_UiManager.php
  label: "Entity Admin ui manager"
  scope: entity
-
  source: Model/_Entity_UiCollectionProvider.php
  label: "Entity Admin ui collection provider"
  scope: entity

