Test/Unit/Block/Adminhtml/Button/Entity/DeleteTest.php:
  destination: Test/Unit/Block/Adminhtml/Button/_Entity_/DeleteTest.php
  label: "Entity Delete button unit test"
  scope: entity
  template: source/Test/Unit/Block/Adminhtml/Button/Entity/DeleteTest.php.html.twig
Test/Unit/Controller/Adminhtml/Entity/DeleteTest.php:
  destination: Test/Unit/Controller/Adminhtml/_Entity_/DeleteTest.php
  label: "Entity Delete action unit test"
  scope: entity
  template: source/Test/Unit/Controller/Adminhtml/Entity/DeleteTest.php.html.twig
Test/Unit/Controller/Adminhtml/Entity/EditTest.php:
  destination: Test/Unit/Controller/Adminhtml/_Entity_/EditTest.php
  label: "Entity Edit action unit test"
  scope: entity
  template: source/Test/Unit/Controller/Adminhtml/Entity/EditTest.php.html.twig
Test/Unit/Model/Entity/Executor/DeleteTest.php:
  destination: Test/Unit/Model/_Entity_/Executor/DeleteTest.php
  label: "Entity delete executor unit test"
  scope: entity
  template: source/Test/Unit/Model/Entity/Executor/DeleteTest.php.html.twig
