







Block/Entity/ListEntity.php:
  destination: Block/_Entity_/List_Entity_.php
  label: "Entity list block"
  scope: entity
  template: source/Block/Entity/ListEntity.php.html.twig
Block/Entity/Link.php:
  destination: Block/_Entity_/Link.php
  label: "Entity link"
  scope: entity
  template: source/Block/Entity/Link.php.html.twig
Block/Entity/ViewEntity.php:
  destination: Block/_Entity_/View_Entity_.php
  label: "Entity view block"
  scope: entity
  template: source/Block/Entity/ViewEntity.php.html.twig
view/frontend/layout/namespace_module_entity_index.xml:
  destination: view/frontend/layout/_namespace___modulename___entity__index.xml
  label: "Entity frontend index layout handle"
  scope: entity
  template: source/view/frontend/layout/namespace_module_name_entity_index.xml.html.twig
view/frontend/layout/namespace_module_entity_view.xml:
  destination: view/frontend/layout/_namespace___modulename___entity__view.xml
  label: "Entity frontend view layout handle"
  scope: entity
  template: source/view/frontend/layout/namespace_module_name_entity_view.xml.html.twig

view/frontend/templates/entity/view.phtml:
  destination: view/frontend/templates/_entity_/view.phtml
  label: "Entity frontend view template"
  scope: entity
  template: source/view/frontend/templates/entity/view.phtml.html.twig
view/frontend/templates/entity/list.phtml:
  destination: view/frontend/templates/_entity_/list.phtml
  label: "Entity frontend list template"
  scope: entity
  template: source/view/frontend/templates/entity/list.phtml.html.twig
