Api/Data/EntityInterface.php:
  destination: Api/Data/_Entity_Interface.php
  label: "Entity data interface"
  scope: entity
  template: source/Api/Data/EntityInterface.php.html.twig
Api/Data/EntitySearchResultInterface.php:
  destination: Api/Data/_Entity_SearchResultInterface.php
  label: "Entity search result interface"
  scope: entity
  template: source/Api/Data/EntitySearchResultInterface.php.html.twig
Api/EntityRepositoryInterface.php:
  destination: Api/_Entity_RepositoryInterface.php
  label: "Entity repository interface"
  scope: entity
  template: source/Api/EntityRepositoryInterface.php.html.twig
Model/Entity.php:
  destination: Model/_Entity_.php
  label: "Entity model"
  scope: entity
  template: source/Model/Entity.php.html.twig
Model/EntityRepository.php:
  destination: Model/_Entity_Repository.php
  label: "Entity repository model"
  scope: entity
  template: source/Model/EntityRepository.php.html.twig
Model/Entity/Executor/Delete.php:
  destination: Model/_Entity_/Executor/Delete.php
  label: "Entity mass action delete executor"
  scope: entity
  template: source/Model/Entity/Executor/Delete.php.html.twig
Model/Entity/CollectionProvider.php:
  destination: Model/_Entity_/CollectionProvider.php
  label: "Entity mass action collection retriever"
  scope: entity
  template: source/Model/Entity/CollectionProvider.php.html.twig
Model/Entity/DataProvider.php:
  destination: Model/_Entity_/DataProvider.php
  label: "Entity admin form data provider"
  scope: entity
  template: source/Model/Entity/DataProvider.php.html.twig
Model/ResourceModel/Entity.php:
  destination: Model/ResourceModel/_Entity_.php
  label: "Entity resource model"
  scope: entity
  template: source/Model/ResourceModel/Entity.php.html.twig
Model/ResourceModel/Entity/Collection.php:
  destination: Model/ResourceModel/_Entity_/Collection.php
  label: "Entity collection resource model"
  scope: entity
  template: source/Model/ResourceModel/Entity/Collection.php.html.twig
Model/Search/Entity.php:
  destination: Model/Search/_Entity_.php
  label: "Entity admin search model"
  scope: entity
  template: source/Model/Search/Entity.php.html.twig
Controller/Adminhtml/Entity/Index.php:
  destination: Controller/Adminhtml/_Entity_/Index.php
  label: "Entity index controller action"
  scope: entity
  template: source/Controller/Adminhtml/Entity/Index.php.html.twig
Controller/Adminhtml/Entity/InlineEdit.php:
  destination: Controller/Adminhtml/_Entity_/InlineEdit.php
  label: "Entity Inline Edit controller action"
  scope: entity
  template: source/Controller/Adminhtml/Entity/InlineEdit.php.html.twig
Controller/Adminhtml/Entity/Save.php:
  destination: Controller/Adminhtml/_Entity_/Save.php
  label: "Entity Save controller action"
  scope: entity
  template: source/Controller/Adminhtml/Entity/Save.php.html.twig
Controller/Adminhtml/Entity/NewAction.php:
  destination: Controller/Adminhtml/_Entity_/NewAction.php
  label: "New entity controller action"
  scope: entity
  template: source/Controller/Adminhtml/Entity/NewAction.php.html.twig
Controller/Adminhtml/Entity/Edit.php:
  destination: Controller/Adminhtml/_Entity_/Edit.php
  label: "Edit entity controller action"
  scope: entity
  template: source/Controller/Adminhtml/Entity/Edit.php.html.twig
Controller/Adminhtml/Entity/Delete.php:
  destination: Controller/Adminhtml/_Entity_/Delete.php
  label: "Delete entity controller action"
  scope: entity
  template: source/Controller/Adminhtml/Entity/Delete.php.html.twig
Controller/Adminhtml/Entity/MassDelete.php:
  destination: Controller/Adminhtml/_Entity_/MassDelete.php
  label: "Mass delete entity controller action"
  scope: entity
  template: source/Controller/Adminhtml/Entity/MassDelete.php.html.twig
Controller/Adminhtml/Entity/File/Upload.php:
  destination: Controller/Adminhtml/_Entity_/File/Upload.php
  label: "Entity file upload controller action"
  scope: entity
  template: source/Controller/Adminhtml/Entity/File/Upload.php.html.twig
Controller/Adminhtml/Entity/Image/Upload.php:
  destination: Controller/Adminhtml/_Entity_/Image/Upload.php
  label: "Entity image upload controller action"
  scope: entity
  template: source/Controller/Adminhtml/Entity/Image/Upload.php.html.twig
Ui/Component/Listing/Column/EntityActions.php:
  destination: Ui/Component/Listing/Column/_Entity_Actions.php
  label: "Entity Grid actions"
  scope: entity
  template: source/Ui/Component/Listing/Column/EntityActions.php.html.twig
Block/Adminhtml/Button/Entity//Delete.php:
  destination: Block/Adminhtml/Button/_Entity_/Delete.php
  label: "Entity Delete button"
  scope: entity
  template: source/Block/Adminhtml/Button/Entity/Delete.php.html.twig
view/admminhtml/layout/namespace_module_entity_edit.xml:
  destination: view/adminhtml/layout/_namespace___module_name___entity__edit.xml
  label: "Entity admin edit layout handle"
  scope: entity
  template: source/view/adminhtml/layout/namespace_module_name_entity_edit.xml.html.twig
view/admminhtml/layout/namespace_module_entity_index.xml:
  destination: view/adminhtml/layout/_namespace___module_name___entity__index.xml
  label: "Entity admin index layout handle"
  scope: entity
  template: source/view/adminhtml/layout/namespace_module_name_entity_index.xml.html.twig
source/view/adminhtml/ui_component/namespace_module_name_entity_listing.xml:
  destination: view/adminhtml/ui_component/_namespace___module_name___entity__listing.xml
  label: "Entity admin grid ui component"
  scope: entity
  template: source/view/adminhtml/ui_component/namespace_module_name_entity_listing.xml.html.twig
source/view/adminhtml/ui_component/namespace_module_name_entity_form.xml:
  destination: view/adminhtml/ui_component/_namespace___module_name___entity__form.xml
  label: "Entity admin grid ui component"
  scope: entity
  template: source/view/adminhtml/ui_component/namespace_module_name_entity_form.xml.html.twig
