





etc/adminhtml/system.xml:
  destination: etc/adminhtml/system.xml
  label: "Admin system file"
  scope: module
  template: source/etc/adminhtml/system.xml.html.twig
etc/frontend/routes.xml:
  destination: etc/frontend/routes.xml
  label: "Frontend routes file"
  scope: module
  template: source/etc/frontend/routes.xml.html.twig
etc/frontend/di.xml:
  destination: etc/frontend/di.xml
  label: "Frontend DI file"
  scope: module
  template: source/etc/frontend/di.xml.html.twig
etc/db_schema.xml:
  destination: etc/db_schema.xml
  label: "Declarative schema file for 2.3+"
  scope: module
  template: source/etc/db_schema.xml.html.twig


Model/UploaderPool.php:
  destination: Model/UploaderPool.php
  label: "Pool of uploaders"
  scope: module
  template: source/Model/UploaderPool.php.html.twig

Model/DateFilter.php:
  destination: Model/DateFilter.php
  label: "Filter for date inputs"
  scope: module
  template: source/Model/DateFilter.php.html.twig
Model/UploadPath.php:
  destination: Model/UploadPath.php
  label: "Upload paths for all entities"
  scope: module
  template: source/Model/UploadPath.php.html.twig
Model/Source/ProductAttribute.php:
  destination: Model/Source/ProductAttribute.php
  label: "Product Attribute Source Model"
  scope: module
  template: source/Model/Source/ProductAttribute.php.html.twig
Model/Source/ProductAttributeSet.php:
  destination: Model/Source/ProductAttributeSet.php
  label: "Product Attribute Set Source Model"
  scope: module
  template: source/Model/Source/ProductAttributeSet.php.html.twig
Model/Output.php:
  destination: Model/Output.php
  label: "Model for filtering wysiwyg output"
  scope: module
  template: source/Model/Output.php.html.twig
Model/Image.php:
  destination: Model/Image.php
  label: "Image model"
  scope: module
  template: source/Model/Image.php.html.twig




Block/Image.php:
  destination: Block/Image.php
  label: "Block for handling images"
  scope: module
  template: source/Block/Image.php.html.twig
Block/ImageBuilder.php:
  destination: Block/ImageBuilder.php
  label: "Block for resizing images"
  scope: module
  template: source/Block/ImageBuilder.php.html.twig
Plugin/Block/TopmenuPlugin.php:
  destination: Plugin/Block/TopmenuPlugin.php
  label: "Frontned Top menu block plugin"
  scope: module
  template: source/Plugin/Block/TopmenuPlugin.php.html.twig
Helper/Image.php:
  destination: Helper/Image.php
  label: "Image helper"
  scope: module
  template: source/Helper/Image.php.html.twig
view/adminhtml/web/template/image-preview.html:
  destination: view/adminhtml/web/template/image-preview.html
  label: "Image preview template"
  scope: module
  template: source/view/adminhtml/web/template/image-preview.html.html.twig
view/adminhtml/web/template/file-preview.html:
  destination: view/adminhtml/web/template/file-preview.html
  label: "File preview template"
  scope: module
  template: source/view/adminhtml/web/template/file-preview.html.html.twig
view/frontend/templates/image.phtml:
  destination: view/frontend/templates/image.phtml
  label: "Image template for frontend"
  scope: module
  template: source/view/frontend/templates/image.phtml.html.twig
view/frontend/templates/image_with_borders.phtml:
  destination: view/frontend/templates/image_with_borders.phtml
  label: "Image with borders template for frontend"
  scope: module
  template: source/view/frontend/templates/image_with_borders.phtml.html.twig
view/frontend/layout/default.xml:
  destination: view/frontend/layout/default.xml
  label: "Default layout handle"
  scope: module
  template: source/view/frontend/layout/default.xml.html.twig


