attribute:
  fields:
    -
      name: type
      options: '%magento_attribute_type%'
    -
      name: full_text
      type: checkbox
      has_default: true
      label: Full text
      title: This adds the attribute to the full text search index of the entity
      additionalDataBind: "enable: data.type() === 'text' || data.type() === 'textarea' || data.type() === 'wysiwyg' || data.type() === 'country' || data.type() === 'country_multiselect'"
      tab: admin
      sort_order: 55
    -
      name: admin_grid_hidden
      type: checkbox
      has_default: true
      label: Hidden by default
      title: "This will hide the column by default"
      additionalDataBind: "enable: (data.type() !== 'file' && data.type() !== 'wysiwyg' && data.type() !== 'dynamic') && data.admin_grid()"
      tab: admin
      sort_order: 70
    -
      name: admin_grid_filter
      type: checkbox
      has_default: true
      label: Filterable in admin grid
      title: If this is set to yes, your field will be filtrable in the admin grid
      additionalDataBind: 'enable:canFilterInAdmin'
      tab: admin
      sort_order: 90
    -
      name: expanded
      type: checkbox
      has_default: true
      label: Display Expanded
      title: If set yo "Yes" each field in the dynamic rows group will be displayed on a separate line. If set to "No" they will all be on the same line
      additionalDataBind: "enable: data.type() === 'dynamic'"
      tab: admin
      sort_order: 100
