-
  source: "@UmcSylius/source/src/_Namespace_/Bundle/_ModuleName_Bundle/Resources/config/doctrine/_Entity_.orm.xml"
  label: "Entity Doctrine declaration file"
  scope: entity
-
  source: "@UmcSylius/source/src/_Namespace_/Bundle/_ModuleName_Bundle/Resources/config/grid/_entity_.yml"
  label: "Entity Grid declaration file"
  scope: entity
-
  source: "@UmcSylius/source/src/_Namespace_/Bundle/_ModuleName_Bundle/Entity/_Entity_.php"
  label: "Entity Model"
  scope: entity
