index:
  path: /
  controller: App\Controller\Index::run
  methods:
    - GET
edit:
  path: /edit
  controller: App\Controller\Edit::run
  methods:
    - GET
save:
  path: /save
  controller: App\Controller\Save::run
  methods:
    - POST
files:
  path: /files
  controller: App\Controller\Files::run
  methods:
  - GET
settings:
  path: /settings
  controller: App\Controller\Settings::run
  methods:
  - GET
save-settings:
  path: /save-settings
  controller: App\Controller\SaveSettings::run
  methods:
  - POST
docs:
  path: /docs
  controller: App\Controller\Docs::run
  methods:
  - GET
