admin_menu:
  value:
    '':
      label: '--Top Level--'
attribute_type:
  flags:
    sort: label
    filter: disabled
  value:
    text:
      label: Text
      input_type: Text Input
      can_be_dynamic: true
      flags:
        can_be_name: true
        can_be_required: true
        can_show_in_grid: true
        full_text: true
    country:
      label: Country
      input_type: Select
      can_be_dynamic: true
      flags:
        can_show_in_grid: true
        can_be_required: true
        full_text: true
    country_multiselect:
      label: Country Multiselect
      input_type: Multiselect
      can_be_dynamic: true
      flags:
        multiple: true
        can_show_in_grid: true
        can_be_required: true
        full_text: true
    date:
      label: Date
      input_type: Date
      can_be_dynamic: true
      flag:
        can_show_in_grid: true
        can_be_required: true
    decimal:
      label: Decimal
      input_type: Text Input
      can_be_dynamic: true
      flags:
        can_show_in_grid: true
        can_be_required: true
    dropdown:
      label: Dropdown
      class: App\Model\Attribute\Type\Dropdown
      input_type: Select
      can_be_dynamic: true
      flags:
        manual_options: true
        can_show_in_grid: true
        can_be_required: true
    file:
      label: File
      can_be_dynamic: false
      input_type: File
      flags:
        upload: true
        full_text: true
    image:
      label: Image
      input_type: File
      can_be_dynamic: false
      flags:
        can_show_in_grid: true
        upload: true
        full_text: true
    integer:
      label: Integer
      input_type: Text Input
      can_be_dynamic: true
      flags:
        can_show_in_grid: true
        can_be_required: true
    multiselect:
      label: Multiselect
      input_type: Multiselect
      can_be_dynamic: true
      flags:
        manual_options: true
        multiple: true
        can_show_in_grid: true
        can_be_required: true
    textarea:
      label: Textarea (no editor)
      can_be_name: false
      input_type: Textarea
      can_be_dynamic: true
      flags:
        can_show_in_grid: true
        can_be_required: true
        full_text: true
    wysiwyg:
      label: Wysiwyg
      input_type: Textarea
      can_be_dynamic: false
      flags:
        can_be_required: true
        full_text: true
    yesno:
      label: Yes/No
      source_model: Magento\Config\Model\Config\Source\Yesno
      input_type: Checkbox (toggle)
      can_be_dynamic: true
      flags:
        can_show_in_grid: true
        can_be_required: true
    product_attribute:
      label: Product Attribute
      input_type: Select
      can_be_dynamic: true
      flags:
        can_show_in_grid: true
        can_be_required: true
    product_attribute_set:
      label: Product Attribute Set
      input_type: Select
      can_be_dynamic: true
      flags:
        can_show_in_grid: true
        can_be_required: true
    product_attribute_multiselect:
      label: Product Attribute Multiselect
      input_type: Multiselect
      can_be_dynamic: true
      flags:
        can_show_in_grid: true
        can_be_required: true
        multiple: true
    product_attribute_set_multiselect:
      label: Product Attribute Set
      input_type: Multiselect
      can_be_dynamic: true
      flags:
        can_show_in_grid: true
        can_be_required: true
        multiple: true
    dynamic:
      label: Dynamic rows
      class: \App\Model\Attribute\Type\Dynamic
      input_type: Dynamic Rows
      can_be_dynamic: false
