shopware:
  code: shopware
  name: Shopware 6
  url: 'https://shopware.com/'
  image: 'bundles/umcshopware/logo/shopware.png'
  sort_order: 20
  config:
    form:
      - '%kernel.project_dir%/src/Umc/CoreBundle/Resources/config/form/module.yml'
      - '%kernel.project_dir%/src/Umc/CoreBundle/Resources/config/form/entity.yml'
      - '%kernel.project_dir%/src/Umc/CoreBundle/Resources/config/form/attribute.yml'
  versions:
    - label: Dummy
      code: dummy
      sort_weight: 10
