-
  source: '@UmcMagento/source/Api/Data/_Entity_Interface.php'
  label: "Entity data interface"
  scope: entity
-
  source: "@UmcMagento/source/Api/Data/_Entity_SearchResultInterface.php"
  label: "Entity search result interface"
  scope: entity
-
  source: "@UmcMagento/source/Api/_Entity_ListRepositoryInterface.php"
  label: "Entity list repository interface"
  scope: entity
-
  source: "@UmcMagento/source/Api/_Entity_RepositoryInterface.php"
  label: "Entity repository interface"
  scope: entity
-
  source: "@UmcMagento/source/Controller/Adminhtml/_Entity_/Index.php"
  label: "Entity index controller action"
  scope: entity
-
  source: "@UmcMagento/source/Controller/Adminhtml/_Entity_/Delete.php"
  label: "Delete entity controller action"
  scope: entity
-
  source: "@UmcMagento/source/Controller/Adminhtml/_Entity_/Edit.php"
  label: "Edit entity controller action"
  scope: entity
-
  source: "@UmcMagento/source/Controller/Adminhtml/_Entity_/NewAction.php"
  label: "New entity controller action"
  scope: entity
-
  source: "@UmcMagento/source/Controller/Adminhtml/_Entity_/InlineEdit.php"
  label: "Inline edit entity controller action"
  scope: entity
-
  source: "@UmcMagento/source/Controller/Adminhtml/_Entity_/MassDelete.php"
  label: "Mass delete entity controller action"
  scope: entity
-
  source: "@UmcMagento/source/Controller/Adminhtml/_Entity_/Save.php"
  label: "Save entity controller action"
  scope: entity
-
  source: "@UmcMagento/source/Controller/Adminhtml/_Entity_/File/Upload.php"
  label: "Entity file upload controller action"
  scope: entity
-
  source: "@UmcMagento/source/Controller/Adminhtml/_Entity_/Image/Upload.php"
  label: "Entity image upload controller action"
  scope: entity
-
  source: "@UmcMagento/source/Model/_Entity_SearchResults.php"
  label: "Entity search results model"
  scope: entity
-
  source: "@UmcMagento/source/Model/_Entity_.php"
  label: "Entity model"
  scope: entity
-
  source: "@UmcMagento/source/Model/ResourceModel/_Entity_.php"
  label: "Entity resource model"
  scope: entity
-
  source: "@UmcMagento/source/Model/ResourceModel/_Entity_/Collection.php"
  label: "Entity collection resource model"
  scope: entity
-
  source: "@UmcMagento/source/view/adminhtml/layout/_modulename___entity__edit.xml"
  label: "Entity admin edit layout handle"
  scope: entity
-
  source: "@UmcMagento/source/view/adminhtml/layout/_modulename___entity__index.xml"
  label: "Entity admin index layout handle"
  scope: entity
-
  source: "@UmcMagento/source/view/adminhtml/ui_component/_modulename___entity__listing.xml"
  label: "Entity admin grid ui component"
  scope: entity
-
  source: "@UmcMagento/source/view/adminhtml/ui_component/_modulename___entity__form.xml"
  label: "Entity admin grid ui component"
  scope: entity
-
  source: "@UmcMagento/source/Model/_Entity_Repo.php"
  label: "Entity repository model"
  scope: entity
-
  source: "@UmcMagento/source/Model/_Entity_ListRepo.php"
  label: "Entity List repository model"
  scope: entity
-
  source: "@UmcMagento/source/Model/_Entity_UiManager.php"
  label: "Entity Admin ui manager"
  scope: entity
-
  source: "@UmcMagento/source/Model/_Entity_UiCollectionProvider.php"
  label: "Entity Admin ui collection provider"
  scope: entity
-
  source: "@UmcMagento/source/Model/Search/_Entity_.php"
  label: "Entity admin search model"
  scope: entity
-
  source: "@UmcMagento/source/ViewModel/_Entity_/Url.php"
  label: "Entity url view model"
  scope: entity
-
  source: "@UmcMagento/source/Controller/_Entity_/Index.php"
  label: "Entity frontend index controller action"
  scope: entity
-
  source: "@UmcMagento/source/Controller/_Entity_/View.php"
  label: "Entity frontend View controller action"
  scope: entity
-
  source: "@UmcMagento/source/ViewModel/_Entity_/List_Entity_.php"
  label: "Entity frontend List view action"
  scope: entity
-
  source: "@UmcMagento/source/ViewModel/_Entity_/View.php"
  label: "Entity frontend view action"
  scope: entity
-
  source: "@UmcMagento/source/view/frontend/layout/_modulename___entity__index.xml"
  label: "Entity frontend list layout handle"
  scope: entity
-
  source: "@UmcMagento/source/view/frontend/layout/_modulename___entity__view.xml"
  label: "Entity frontend list layout handle"
  scope: entity
-
  source: "@UmcMagento/source/view/frontend/templates/_entity_/view.phtml"
  label: "Entity frontend view template"
  scope: entity
-
  source: "@UmcMagento/source/view/frontend/templates/_entity_/list.phtml"
  label: "Entity frontend list template"
  scope: entity
